#!/bin/bash

echo "🌐 Grafana Dashboard Access Information"
echo "======================================"
echo ""
echo "📊 Available Dashboards:"
echo "1. Enterprise Aspire Dashboard (UID: enterprise-aspire)"
echo "2. Infrastructure Health Dashboard (UID: infrastructure-health)"
echo "3. Basic Metrics Debug (UID: basic-metrics)"
echo ""
echo "🔗 Direct Access URLs:"
echo "Enterprise Aspire: http://localhost:3000/d/enterprise-aspire/enterprise-aspire-dashboard"
echo "Infrastructure Health: http://localhost:3000/d/infrastructure-health/infrastructure-health-dashboard"
echo "Basic Metrics: http://localhost:3000/d/basic-metrics/basic-metrics-debug"
echo ""
echo "🔑 Default Credentials:"
echo "Username: admin"
echo "Password: admin"
echo ""
echo "📚 Documentation:"
echo "Dashboard Guide: DASHBOARDS_README.md"
echo "Infrastructure Setup: ../README.md"
echo ""
echo "💡 Quick Start:"
echo "1. Ensure infrastructure is running: cd .. && ./start-aspire.sh"
echo "2. Open Grafana: http://localhost:3000"
echo "3. Login with admin/admin"
echo "4. Navigate to Dashboards → Browse"
echo "5. Access Keycloak: http://localhost:8080/admin (admin/admin)"
echo ""
echo "🔐 Authentication Services:"
echo "   Keycloak: http://localhost:8080/admin"
echo "   PostgreSQL: localhost:5432 (keycloak/secret)"
echo ""
echo "🚨 Troubleshooting:"
echo "- If dashboards don't appear, check Prometheus data source"
echo "- Verify all services are running and exposing metrics"
echo "- Check infrastructure/monitoring/grafana/ for dashboard files"
